DROP TABLE IF EXISTS `Characters`;

-- Create Characters Table
CREATE TABLE Characters (
	id INT NOT NULL AUTO_INCREMENT,
	F_name VARCHAR(255) NOT NULL,
	L_name VARCHAR(255),
	Title VARCHAR(255),
	isAlive INT,
	CityID INT,
	HouseID INT,
	PRIMARY KEY (id),
	CONSTRAINT CityFK FOREIGN KEY (CityID) REFERENCES City (id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT HouseFK FOREIGN KEY (HouseID) REFERENCES House (id) ON DELETE CASCADE ON UPDATE CASCADE,
	UNIQUE KEY (F_name, L_name) 
) ENGINE=InnoDB;
