DROP TABLE IF EXISTS `City`;

-- Create City Table
CREATE TABLE City (
	id INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(255) NOT NULL UNIQUE,
	RegionID INT,
	PRIMARY KEY(id),
	CONSTRAINT RegionFK FOREIGN KEY (RegionID) REFERENCES Region (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;