INSERT INTO Region (Name, Continent) 
	VALUES ('BEYOND THE WALL','WESTEROS'),
		('THE NORTH','WESTEROS'),
		('THE WALL','WESTEROS'),
		('THE RIVERLANDS','WESTEROS'),
		('THE VALE','WESTEROS'),
		('THE IRON ISLANDS','WESTEROS'),
		('THE WESTERLANDS','WESTEROS'),
		('THE REACH','WESTEROS'),
		('THE CROWNLANDS','WESTEROS'),
		('THE STORMLANDS','WESTEROS'),
		('DORNE','WESTEROS'),
		('FREE CITIES','ESSOS'),
		('SLAVERS BAY','ESSOS'),
		('DOTHRAKI SEA','ESSOS'),
		('RED WASTE','ESSOS'),
		('QARTH','ESSOS'),
		('VALYRIAN PENINSULA','ESSOS'),
		('NAATH','SOTHORYOS'),
		('SUMMER SEA','SOTHORYOS'); 

-- Houses
INSERT INTO House (Name, Motto) 
	VALUES ('ARRYN','AS HIGH AS HONOR'), 
		('BARATHEON','OURS IS THE FURY'),
		('LANNISTER','HEAR ME ROAR!'), 
		('MARTELL','UNBOWED, UNBENT, UNBROKEN'),
		('TULLY','FAMILY, DUTY, HONOR'), 
		('TYRELL','GROWING STRONG'), 
		('GREYJOY','WE DO NOT SOW'), 
		('TARGARYEN','FIRE AND BLOOD'), 
		('STARK','WINTER IS COMING'), 
		('BOLTON','OUR BLADES ARE SHARP');

-- Connection Types
INSERT INTO Connection_Type (Description) 
	VALUES ('SON'),
		('DAUGHTER'),
		('HUSBAND'),
		('WIFE'),
		('BROTHER'),
		('SISTER'),
		('COUSIN'),
		('MOTHER'),
		('FATHER'),
		('UNCLE'),
		('AUNT'),
		('ALLY'),
		('LOVER'),
		('KILLER'),
		('NIECE'),
		('NEPHEW');

-- Cities
INSERT INTO City (Name, RegionID) 
	VALUES ('WINTERFELL', (SELECT id FROM Region WHERE Name = 'THE NORTH')),
		('BEAR ISLAND', (SELECT id FROM Region WHERE Name = 'THE NORTH')),
		('DREADFORT', (SELECT id FROM Region WHERE Name = 'THE NORTH')),
		('CASTLE BLACK', (SELECT id FROM Region WHERE Name = 'THE WALL')),
		('CRASTERS KEEP', (SELECT id FROM Region WHERE Name = 'BEYOND THE WALL')),
		('PYKE', (SELECT id FROM Region WHERE Name = 'THE IRON ISLANDS')),
		('THE FINGERS', (SELECT id FROM Region WHERE Name = 'THE VALE')),
		('CASTERLY ROCK', (SELECT id FROM Region WHERE Name = 'THE WESTERLANDS')),
		('LANNISPORT', (SELECT id FROM Region WHERE Name = 'THE WESTERLANDS')),
		('RIVERRUN', (SELECT id FROM Region WHERE Name = 'THE RIVERLANDS')),
		('HIGHGARDEN', (SELECT id FROM Region WHERE Name = 'THE REACH')),
		('HORN HILL', (SELECT id FROM Region WHERE Name = 'THE REACH')),
		('KINGS LANDING', (SELECT id FROM Region WHERE Name = 'THE CROWNLANDS')),
		('BLACKWATER BAY', (SELECT id FROM Region WHERE Name = 'THE CROWNLANDS')),
		('STORMS END', (SELECT id FROM Region WHERE Name = 'THE STORMLANDS')),
		('TARTH', (SELECT id FROM Region WHERE Name = 'THE STORMLANDS')),
		('SUNSPEAR', (SELECT id FROM Region WHERE Name = 'DORNE')),
		('HELLHOLT', (SELECT id FROM Region WHERE Name = 'DORNE')),
		('BRAAVOS', (SELECT id FROM Region WHERE Name = 'FREE CITIES')),
		('TYROSH', (SELECT id FROM Region WHERE Name = 'FREE CITIES')),
		('LYS', (SELECT id FROM Region WHERE Name = 'FREE CITIES')),
		('VOLANTIS', (SELECT id FROM Region WHERE Name = 'FREE CITIES')),
		('PENTOS', (SELECT id FROM Region WHERE Name = 'FREE CITIES')),
		('MEEREEN', (SELECT id FROM Region WHERE Name = 'SLAVERS BAY')),
		('VAES DOTHRAK', (SELECT id FROM Region WHERE Name = 'DOTHRAKI SEA')),
		('ASSHAI', (SELECT id FROM Region WHERE Name = 'DOTHRAKI SEA')),
		('SUMMER ISLES', (SELECT id FROM Region WHERE Name = 'SUMMER SEA'))
		('NAATH', (SELECT id FROM Region WHERE Name = 'NAATH')); 

-- Characters
INSERT INTO Characters (F_name, L_name, Title, isAlive, CityID, HouseID) 
	VALUES ('JON', 'SNOW', 'KING IN THE NORTH', 1, (SELECT id FROM City WHERE Name = 'WINTERFELL'), (SELECT id FROM House WHERE Name = 'STARK')),
		('BRAN', 'STARK', 'PRINCE', 1, (SELECT id FROM City WHERE Name = 'WINTERFELL'), (SELECT id FROM House WHERE Name = 'STARK')),
		('SANSA', 'STARK', 'PRINCESS', 1, (SELECT id FROM City WHERE Name = 'WINTERFELL'), (SELECT id FROM House WHERE Name = 'STARK')),
		('ARYA', 'STARK', 'PRINCESS', 1, (SELECT id FROM City WHERE Name = 'WINTERFELL'), (SELECT id FROM House WHERE Name = 'STARK')),
		('EDDARD', 'STARK', 'LORD', 0, (SELECT id FROM City WHERE Name = 'WINTERFELL'), (SELECT id FROM House WHERE Name = 'STARK')),
		('CATELYN', 'STARK', 'LADY', 0, (SELECT id FROM City WHERE Name = 'RIVERRUN'), (SELECT id FROM House WHERE Name = 'STARK')),
		('ROBB', 'STARK', 'KING', 0, (SELECT id FROM City WHERE Name = 'WINTERFELL'), (SELECT id FROM House WHERE Name = 'STARK')),
		('RICKON', 'STARK', 'PRINCE', 0, (SELECT id FROM City WHERE Name = 'WINTERFELL'), (SELECT id FROM House WHERE Name = 'STARK')),
		('LYANNA', 'STARK', NULL, 0, (SELECT id FROM City WHERE Name = 'WINTERFELL'), (SELECT id FROM House WHERE Name = 'STARK')),
		('BENJEN', 'STARK', 'FIRST RANGER', 1, (SELECT id FROM City WHERE Name = 'WINTERFELL'), (SELECT id FROM House WHERE Name = 'STARK')),
		('TALISA', 'STARK', 'QUEEN', 0, (SELECT id FROM City WHERE Name = 'VOLANTIS'), (SELECT id FROM House WHERE Name = 'STARK')),

		('CERSEI', 'LANNISTER', 'QUEEN MOTHER', 1, (SELECT id FROM City WHERE Name = 'CASTERLY ROCK'), (SELECT id FROM House WHERE Name = 'LANNISTER')),
		('JAIME', 'LANNISTER', 'SER', 1, (SELECT id FROM City WHERE Name = 'CASTERLY ROCK'), (SELECT id FROM House WHERE Name = 'LANNISTER')),
		('LANCEL', 'LANNISTER', 'SER', 0, (SELECT id FROM City WHERE Name = 'CASTERLY ROCK'), (SELECT id FROM House WHERE Name = 'LANNISTER')),
		('TYRION', 'LANNISTER', 'LORD', 1, (SELECT id FROM City WHERE Name = 'CASTERLY ROCK'), (SELECT id FROM House WHERE Name = 'LANNISTER')),
		('TYWIN', 'LANNISTER', 'LORD', 0, (SELECT id FROM City WHERE Name = 'CASTERLY ROCK'), (SELECT id FROM House WHERE Name = 'LANNISTER')),
		('MYRCELLA', 'BARATHEON', 'PRINCESS', 0, (SELECT id FROM City WHERE Name = 'KINGS LANDING'), (SELECT id FROM House WHERE Name = 'BARATHEON')),
		('JOFFREY', 'BARATHEON', 'KING', 0, (SELECT id FROM City WHERE Name = 'KINGS LANDING'), (SELECT id FROM House WHERE Name = 'BARATHEON')),
		('TOMMEN', 'BARATHEON', 'KING', 0, (SELECT id FROM City WHERE Name = 'KINGS LANDING'), (SELECT id FROM House WHERE Name = 'BARATHEON')),
		('MARGAERY', 'TYRELL', 'QUEEN', 0, (SELECT id FROM City WHERE Name = 'HIGHGARDEN'), (SELECT id FROM House WHERE Name = 'TYRELL')),
		('LORAS', 'TYRELL', 'SER', 0, (SELECT id FROM City WHERE Name = 'HIGHGARDEN'), (SELECT id FROM House WHERE Name = 'TYRELL')),

		('ROBERT', 'BARATHEON', 'KING', 0, (SELECT id FROM City WHERE Name = 'STORMS END'), (SELECT id FROM House WHERE Name = 'BARATHEON')),
		('STANNIS', 'BARATHEON', 'LORD', 0, (SELECT id FROM City WHERE Name = 'STORMS END'), (SELECT id FROM House WHERE Name = 'BARATHEON')),
		('RENLY', 'BARATHEON', 'LORD', 0, (SELECT id FROM City WHERE Name = 'STORMS END'), (SELECT id FROM House WHERE Name = 'BARATHEON')),
		('MELISANDRE', NULL, 'RED PRIESTESS', 1, (SELECT id FROM City WHERE Name = 'ASSHAI'), NULL),
		('DAVOS', 'SEAWORTH', NULL, 1, (SELECT id FROM City WHERE Name = 'KINGS LANDING'), NULL),
		('BRIENNE', 'TARTH', 'LADY', 1, (SELECT id FROM City WHERE Name = 'TARTH'), NULL),

		('PETYR', 'BAELISH', 'LORD', 1, (SELECT id FROM City WHERE Name = 'THE FINGERS'), NULL),
		('EURON', 'GREYJOY', 'KING', 1, (SELECT id FROM City WHERE Name = 'PYKE'), (SELECT id FROM House WHERE Name = 'GREYJOY')),
		('BALON', 'GREYJOY', 'KING', 0, (SELECT id FROM City WHERE Name = 'PYKE'), (SELECT id FROM House WHERE Name = 'GREYJOY')),
		('THEON', 'GREYJOY', NULL, 1, (SELECT id FROM City WHERE Name = 'PYKE'), (SELECT id FROM House WHERE Name = 'GREYJOY')),
		('YARA', 'GREYJOY', NULL, 1, (SELECT id FROM City WHERE Name = 'PYKE'), (SELECT id FROM House WHERE Name = 'GREYJOY')),
		('ROOSE', 'BOLTON', NULL, 0, (SELECT id FROM City WHERE Name = 'DREADFORT'), (SELECT id FROM House WHERE Name = 'BOLTON')),
		('RAMSAY', 'BOLTON', NULL, 0, (SELECT id FROM City WHERE Name = 'DREADFORT'), (SELECT id FROM House WHERE Name = 'BOLTON')),
				
		('SAMWELL', 'TARLY', NULL, 1, (SELECT id FROM City WHERE Name = 'HORN HILL'), NULL),
		('GILLY', NULL, NULL, 1, (SELECT id FROM City WHERE Name = 'CRASTERS KEEP'), NULL),

		('DAENERYS', 'TARGARYEN', 'MOTHER OF DRAGONS', 1, (SELECT id FROM City WHERE Name = 'BLACKWATER BAY'), (SELECT id FROM House WHERE Name = 'TARGARYEN')),
		('RHAEGAR', 'TARGARYEN', 'PRINCE', 0, (SELECT id FROM City WHERE Name = 'BLACKWATER BAY'), (SELECT id FROM House WHERE Name = 'TARGARYEN')),
		('MISSANDEI', NULL, NULL, 1, (SELECT id FROM City WHERE Name = 'NAATH'), NULL),
		('GREY', 'WORM', NULL, 1, (SELECT id FROM City WHERE Name = 'SUMMER ISLES'), NULL),
		('DAARIO', 'NAHARIS', NULL, 1, (SELECT id FROM City WHERE Name = 'TYROSH'), NULL),
		('JORAH', 'MORMONT', NULL, 1, (SELECT id FROM City WHERE Name = 'BEAR ISLAND'), NULL),
		('KHAL', 'DROGO', NULL, 0, (SELECT id FROM City WHERE Name = 'VAES DOTHRAK'), NULL),

		('DORAN', 'MARTELL', NULL, 0, (SELECT id FROM City WHERE Name = 'SUNSPEAR'), (SELECT id FROM House WHERE Name = 'MARTELL')),
		('OBERYN', 'MARTELL', 'PRINCE', 0, (SELECT id FROM City WHERE Name = 'SUNSPEAR'), (SELECT id FROM House WHERE Name = 'MARTELL')),
		('TRYSTANE', 'MARTELL', NULL, 0, (SELECT id FROM City WHERE Name = 'SUNSPEAR'), (SELECT id FROM House WHERE Name = 'MARTELL')),
		('ELLARIA', 'SAND', NULL, 1, (SELECT id FROM City WHERE Name = 'HELLHOLT'), NULL),

		('GREGOR', 'CLEGANE', NULL, 1, (SELECT id FROM City WHERE Name = 'CASTERLY ROCK'), NULL),
		('SANDOR', 'CLEGANE', NULL, 1, (SELECT id FROM City WHERE Name = 'CASTERLY ROCK'), NULL),
		
		('EDMURE', 'TULLY', 'LORD', 1, (SELECT id FROM City WHERE Name = 'RIVERRUN'), (SELECT id FROM House WHERE Name = 'TULLY')),
				
		('HODOR', NULL, NULL, 0, (SELECT id FROM City WHERE Name = 'WINTERFELL'), NULL),
		('ELIA', 'MARTELL', NULL, 1, (SELECT id FROM City WHERE Name = 'SUNSPEAR'), (SELECT id FROM House WHERE Name = 'MARTELL'));

-- Ties
INSERT INTO Ties (Char1_ID, Char2_ID, CT_ID) 
	VALUES 
		((SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Characters WHERE F_name = 'LYANNA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SON')),
		((SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Characters WHERE F_name = 'RHAEGAR'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SON')),
		((SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Characters WHERE F_name = 'ROBB'), 
			(SELECT id FROM Connection_Type WHERE Description = 'COUSIN')),
		((SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'COUSIN')),
		((SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Characters WHERE F_name = 'ARYA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'COUSIN')),
		((SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Characters WHERE F_name = 'BRAN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'COUSIN')),
		((SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Characters WHERE F_name = 'RICKON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'COUSIN')),
		((SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Characters WHERE F_name = 'DAENERYS'), 
			(SELECT id FROM Connection_Type WHERE Description = 'NEPHEW')),
		((SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Characters WHERE F_name = 'SAMWELL'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		((SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Characters WHERE F_name = 'DAVOS'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		
		((SELECT id FROM Characters WHERE F_name = 'BRAN'), 
			(SELECT id FROM Characters WHERE F_name = 'CATELYN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SON')),
		((SELECT id FROM Characters WHERE F_name = 'BRAN'), 
			(SELECT id FROM Characters WHERE F_name = 'EDDARD'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SON')),
		((SELECT id FROM Characters WHERE F_name = 'BRAN'), 
			(SELECT id FROM Characters WHERE F_name = 'ROBB'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'BRAN'), 
			(SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'BRAN'), 
			(SELECT id FROM Characters WHERE F_name = 'ARYA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'BRAN'), 
			(SELECT id FROM Characters WHERE F_name = 'RICKON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'BRAN'), 
			(SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'COUSIN')),
		((SELECT id FROM Characters WHERE F_name = 'BRAN'), 
			(SELECT id FROM Characters WHERE F_name = 'HODOR'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		
		((SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Characters WHERE F_name = 'CATELYN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'DAUGHTER')),
		((SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Characters WHERE F_name = 'EDDARD'), 
			(SELECT id FROM Connection_Type WHERE Description = 'DAUGHTER')),
		((SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Characters WHERE F_name = 'ROBB'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SISTER')),
		((SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Characters WHERE F_name = 'BRAN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SISTER')),
		((SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Characters WHERE F_name = 'ARYA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SISTER')),
		((SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Characters WHERE F_name = 'RICKON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SISTER')),
		((SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'COUSIN')),
		((SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Characters WHERE F_name = 'BRIENNE'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		((SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Characters WHERE F_name = 'PETYR'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		((SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Characters WHERE F_name = 'THEON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		((SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Characters WHERE F_name = 'RAMSAY'), 
			(SELECT id FROM Connection_Type WHERE Description = 'KILLER')),

		((SELECT id FROM Characters WHERE F_name = 'ARYA'), 
			(SELECT id FROM Characters WHERE F_name = 'CATELYN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'DAUGHTER')),
		((SELECT id FROM Characters WHERE F_name = 'ARYA'), 
			(SELECT id FROM Characters WHERE F_name = 'EDDARD'), 
			(SELECT id FROM Connection_Type WHERE Description = 'DAUGHTER')),
		((SELECT id FROM Characters WHERE F_name = 'ARYA'), 
			(SELECT id FROM Characters WHERE F_name = 'ROBB'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SISTER')),
		((SELECT id FROM Characters WHERE F_name = 'ARYA'), 
			(SELECT id FROM Characters WHERE F_name = 'BRAN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SISTER')),
		((SELECT id FROM Characters WHERE F_name = 'ARYA'), 
			(SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SISTER')),
		((SELECT id FROM Characters WHERE F_name = 'ARYA'), 
			(SELECT id FROM Characters WHERE F_name = 'RICKON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SISTER')),
		((SELECT id FROM Characters WHERE F_name = 'ARYA'), 
			(SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'COUSIN')),
		
		((SELECT id FROM Characters WHERE F_name = 'EDDARD'), 
			(SELECT id FROM Characters WHERE F_name = 'CATELYN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'HUSBAND')),
		((SELECT id FROM Characters WHERE F_name = 'EDDARD'),
			(SELECT id FROM Characters WHERE F_name = 'ROBB'), 
			(SELECT id FROM Connection_Type WHERE Description = 'FATHER')),
		((SELECT id FROM Characters WHERE F_name = 'EDDARD'),
			(SELECT id FROM Characters WHERE F_name = 'BRAN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'FATHER')),
		((SELECT id FROM Characters WHERE F_name = 'EDDARD'),
			(SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'FATHER')),
		((SELECT id FROM Characters WHERE F_name = 'EDDARD'),
			(SELECT id FROM Characters WHERE F_name = 'RICKON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'FATHER')),
		((SELECT id FROM Characters WHERE F_name = 'EDDARD'), 
			(SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'UNCLE')),
		((SELECT id FROM Characters WHERE F_name = 'EDDARD'), 
			(SELECT id FROM Characters WHERE F_name = 'BENJEN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'EDDARD'), 
			(SELECT id FROM Characters WHERE F_name = 'LYANNA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'EDDARD'), 
			(SELECT id FROM Characters WHERE F_name = 'ROBERT'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),

		((SELECT id FROM Characters WHERE F_name = 'CATELYN'), 
			(SELECT id FROM Characters WHERE F_name = 'EDDARD'), 
			(SELECT id FROM Connection_Type WHERE Description = 'WIFE')),
		((SELECT id FROM Characters WHERE F_name = 'CATELYN'), 
			(SELECT id FROM Characters WHERE F_name = 'ROBB'), 
			(SELECT id FROM Connection_Type WHERE Description = 'MOTHER')),
		((SELECT id FROM Characters WHERE F_name = 'CATELYN'), 
			(SELECT id FROM Characters WHERE F_name = 'BRAN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'MOTHER')),
		((SELECT id FROM Characters WHERE F_name = 'CATELYN'), 
			(SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'MOTHER')),
		((SELECT id FROM Characters WHERE F_name = 'CATELYN'), 
			(SELECT id FROM Characters WHERE F_name = 'RICKON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'MOTHER')),
		((SELECT id FROM Characters WHERE F_name = 'CATELYN'), 
			(SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'AUNT')),
		((SELECT id FROM Characters WHERE F_name = 'CATELYN'), 
			(SELECT id FROM Characters WHERE F_name = 'EDMURE'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SISTER')),
		((SELECT id FROM Characters WHERE F_name = 'CATELYN'), 
			(SELECT id FROM Characters WHERE F_name = 'BRIENNE'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),

		((SELECT id FROM Characters WHERE F_name = 'ROBB'), 
			(SELECT id FROM Characters WHERE F_name = 'CATELYN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SON')),
		((SELECT id FROM Characters WHERE F_name = 'ROBB'), 
			(SELECT id FROM Characters WHERE F_name = 'EDDARD'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SON')),
		((SELECT id FROM Characters WHERE F_name = 'ROBB'), 
			(SELECT id FROM Characters WHERE F_name = 'BRAN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'ROBB'), 
			(SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'ROBB'), 
			(SELECT id FROM Characters WHERE F_name = 'ARYA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'ROBB'), 
			(SELECT id FROM Characters WHERE F_name = 'RICKON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'ROBB'), 
			(SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'COUSIN')),
		((SELECT id FROM Characters WHERE F_name = 'ROBB'), 
			(SELECT id FROM Characters WHERE F_name = 'TALISA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'HUSBAND')),

		((SELECT id FROM Characters WHERE F_name = 'RICKON'), 
			(SELECT id FROM Characters WHERE F_name = 'CATELYN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SON')),
		((SELECT id FROM Characters WHERE F_name = 'RICKON'), 
			(SELECT id FROM Characters WHERE F_name = 'EDDARD'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SON')),
		((SELECT id FROM Characters WHERE F_name = 'RICKON'), 
			(SELECT id FROM Characters WHERE F_name = 'BRAN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'RICKON'), 
			(SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'RICKON'), 
			(SELECT id FROM Characters WHERE F_name = 'ARYA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'RICKON'), 
			(SELECT id FROM Characters WHERE F_name = 'ROBB'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'RICKON'), 
			(SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'COUSIN')),

		((SELECT id FROM Characters WHERE F_name = 'LYANNA'), 
			(SELECT id FROM Characters WHERE F_name = 'EDDARD'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SISTER')),
		((SELECT id FROM Characters WHERE F_name = 'LYANNA'), 
			(SELECT id FROM Characters WHERE F_name = 'BENJEN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SISTER')),
		((SELECT id FROM Characters WHERE F_name = 'LYANNA'), 
			(SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'MOTHER')),

		((SELECT id FROM Characters WHERE F_name = 'BENJEN'), 
			(SELECT id FROM Characters WHERE F_name = 'EDDARD'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'BENJEN'), 
			(SELECT id FROM Characters WHERE F_name = 'LYANNA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),

		((SELECT id FROM Characters WHERE F_name = 'TALISA'), 
			(SELECT id FROM Characters WHERE F_name = 'ROBB'), 
			(SELECT id FROM Connection_Type WHERE Description = 'WIFE')),


		((SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Characters WHERE F_name = 'JAIME'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SISTER')),
		((SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Characters WHERE F_name = 'LANCEL'), 
			(SELECT id FROM Connection_Type WHERE Description = 'COUSIN')),
		((SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Characters WHERE F_name = 'TYRION'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SISTER')),
		((SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Characters WHERE F_name = 'TYWIN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'DAUGHTER')),
		((SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Characters WHERE F_name = 'MYRCELLA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'MOTHER')),
		((SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Characters WHERE F_name = 'JOFFREY'), 
			(SELECT id FROM Connection_Type WHERE Description = 'MOTHER')),
		((SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Characters WHERE F_name = 'TOMMEN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'MOTHER')),
		((SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Characters WHERE F_name = 'ROBERT'), 
			(SELECT id FROM Connection_Type WHERE Description = 'WIFE')),
		((SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Characters WHERE F_name = 'JAIME'), 
			(SELECT id FROM Connection_Type WHERE Description = 'LOVER')),
		((SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Characters WHERE F_name = 'LANCEL'), 
			(SELECT id FROM Connection_Type WHERE Description = 'LOVER')),
		((SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Characters WHERE F_name = 'GREGOR'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		
		((SELECT id FROM Characters WHERE F_name = 'JAIME'), 
			(SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'JAIME'), 
			(SELECT id FROM Characters WHERE F_name = 'LANCEL'), 
			(SELECT id FROM Connection_Type WHERE Description = 'COUSIN')),
		((SELECT id FROM Characters WHERE F_name = 'JAIME'), 
			(SELECT id FROM Characters WHERE F_name = 'TYRION'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'JAIME'), 
			(SELECT id FROM Characters WHERE F_name = 'TYWIN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SON')),
		((SELECT id FROM Characters WHERE F_name = 'JAIME'), 
			(SELECT id FROM Characters WHERE F_name = 'MYRCELLA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'FATHER')),
		((SELECT id FROM Characters WHERE F_name = 'JAIME'), 
			(SELECT id FROM Characters WHERE F_name = 'JOFFREY'), 
			(SELECT id FROM Connection_Type WHERE Description = 'FATHER')),
		((SELECT id FROM Characters WHERE F_name = 'JAIME'), 
			(SELECT id FROM Characters WHERE F_name = 'TOMMEN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'FATHER')),
		((SELECT id FROM Characters WHERE F_name = 'JAIME'), 
			(SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Connection_Type WHERE Description = 'LOVER')),

		((SELECT id FROM Characters WHERE F_name = 'LANCEL'), 
			(SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Connection_Type WHERE Description = 'COUSIN')),
		((SELECT id FROM Characters WHERE F_name = 'LANCEL'), 
			(SELECT id FROM Characters WHERE F_name = 'JAIME'), 
			(SELECT id FROM Connection_Type WHERE Description = 'COUSIN')),
		((SELECT id FROM Characters WHERE F_name = 'LANCEL'), 
			(SELECT id FROM Characters WHERE F_name = 'TYWIN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'NEPHEW')),
		((SELECT id FROM Characters WHERE F_name = 'LANCEL'), 
			(SELECT id FROM Characters WHERE F_name = 'TYRION'), 
			(SELECT id FROM Connection_Type WHERE Description = 'COUSIN')),
		((SELECT id FROM Characters WHERE F_name = 'LANCEL'), 
			(SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Connection_Type WHERE Description = 'LOVER')),

		((SELECT id FROM Characters WHERE F_name = 'TYRION'), 
			(SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'TYRION'), 
			(SELECT id FROM Characters WHERE F_name = 'LANCEL'), 
			(SELECT id FROM Connection_Type WHERE Description = 'COUSIN')),
		((SELECT id FROM Characters WHERE F_name = 'TYRION'), 
			(SELECT id FROM Characters WHERE F_name = 'JAIME'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'TYRION'), 
			(SELECT id FROM Characters WHERE F_name = 'TYWIN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SON')),
		((SELECT id FROM Characters WHERE F_name = 'TYRION'), 
			(SELECT id FROM Characters WHERE F_name = 'DAENERYS'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		((SELECT id FROM Characters WHERE F_name = 'TYRION'), 
			(SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		((SELECT id FROM Characters WHERE F_name = 'TYRION'), 
			(SELECT id FROM Characters WHERE F_name = 'TYWIN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'KILLER')),

		((SELECT id FROM Characters WHERE F_name = 'TYWIN'), 
			(SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Connection_Type WHERE Description = 'FATHER')),
		((SELECT id FROM Characters WHERE F_name = 'TYWIN'), 
			(SELECT id FROM Characters WHERE F_name = 'JAIME'), 
			(SELECT id FROM Connection_Type WHERE Description = 'FATHER')),
		((SELECT id FROM Characters WHERE F_name = 'TYWIN'), 
			(SELECT id FROM Characters WHERE F_name = 'TYRION'), 
			(SELECT id FROM Connection_Type WHERE Description = 'FATHER')),
		((SELECT id FROM Characters WHERE F_name = 'TYWIN'), 
			(SELECT id FROM Characters WHERE F_name = 'LANCEL'), 
			(SELECT id FROM Connection_Type WHERE Description = 'UNCLE')),

		((SELECT id FROM Characters WHERE F_name = 'MYRCELLA'), 
			(SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Connection_Type WHERE Description = 'DAUGHTER')),
		((SELECT id FROM Characters WHERE F_name = 'MYRCELLA'), 
			(SELECT id FROM Characters WHERE F_name = 'JAIME'), 
			(SELECT id FROM Connection_Type WHERE Description = 'DAUGHTER')),
		((SELECT id FROM Characters WHERE F_name = 'MYRCELLA'), 
			(SELECT id FROM Characters WHERE F_name = 'TYRION'), 
			(SELECT id FROM Connection_Type WHERE Description = 'NIECE')),
		((SELECT id FROM Characters WHERE F_name = 'MYRCELLA'), 
			(SELECT id FROM Characters WHERE F_name = 'JOFFREY'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SISTER')),
		((SELECT id FROM Characters WHERE F_name = 'MYRCELLA'), 
			(SELECT id FROM Characters WHERE F_name = 'TOMMEN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SISTER')),
		((SELECT id FROM Characters WHERE F_name = 'MYRCELLA'), 
			(SELECT id FROM Characters WHERE F_name = 'TRYSTANE'), 
			(SELECT id FROM Connection_Type WHERE Description = 'LOVER')),

		((SELECT id FROM Characters WHERE F_name = 'JOFFREY'), 
			(SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SON')),
		((SELECT id FROM Characters WHERE F_name = 'JOFFREY'), 
			(SELECT id FROM Characters WHERE F_name = 'JAIME'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SON')),
		((SELECT id FROM Characters WHERE F_name = 'JOFFREY'), 
			(SELECT id FROM Characters WHERE F_name = 'TYRION'), 
			(SELECT id FROM Connection_Type WHERE Description = 'NEPHEW')),
		((SELECT id FROM Characters WHERE F_name = 'JOFFREY'), 
			(SELECT id FROM Characters WHERE F_name = 'MYRCELLA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'JOFFREY'), 
			(SELECT id FROM Characters WHERE F_name = 'TOMMEN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'JOFFREY'), 
			(SELECT id FROM Characters WHERE F_name = 'MARGAERY'), 
			(SELECT id FROM Connection_Type WHERE Description = 'HUSBAND')),

		((SELECT id FROM Characters WHERE F_name = 'TOMMEN'), 
			(SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SON')),
		((SELECT id FROM Characters WHERE F_name = 'TOMMEN'), 
			(SELECT id FROM Characters WHERE F_name = 'JAIME'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SON')),
		((SELECT id FROM Characters WHERE F_name = 'TOMMEN'), 
			(SELECT id FROM Characters WHERE F_name = 'TYRION'), 
			(SELECT id FROM Connection_Type WHERE Description = 'NEPHEW')),
		((SELECT id FROM Characters WHERE F_name = 'TOMMEN'), 
			(SELECT id FROM Characters WHERE F_name = 'MYRCELLA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'TOMMEN'), 
			(SELECT id FROM Characters WHERE F_name = 'JOFFREY'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'TOMMEN'), 
			(SELECT id FROM Characters WHERE F_name = 'MARGAERY'), 
			(SELECT id FROM Connection_Type WHERE Description = 'HUSBAND')),

		((SELECT id FROM Characters WHERE F_name = 'MARGAERY'), 
			(SELECT id FROM Characters WHERE F_name = 'TOMMEN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'WIFE')),
		((SELECT id FROM Characters WHERE F_name = 'MARGAERY'), 
			(SELECT id FROM Characters WHERE F_name = 'LORAS'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SISTER')),

		((SELECT id FROM Characters WHERE F_name = 'LORAS'), 
			(SELECT id FROM Characters WHERE F_name = 'MARGAERY'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'LORAS'), 
			(SELECT id FROM Characters WHERE F_name = 'RENLY'), 
			(SELECT id FROM Connection_Type WHERE Description = 'LOVER')),


		((SELECT id FROM Characters WHERE F_name = 'ROBERT'), 
			(SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Connection_Type WHERE Description = 'HUSBAND')),
		((SELECT id FROM Characters WHERE F_name = 'ROBERT'), 
			(SELECT id FROM Characters WHERE F_name = 'STANNIS'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'ROBERT'), 
			(SELECT id FROM Characters WHERE F_name = 'RENLY'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'ROBERT'), 
			(SELECT id FROM Characters WHERE F_name = 'EDDARD'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),

		((SELECT id FROM Characters WHERE F_name = 'STANNIS'), 
			(SELECT id FROM Characters WHERE F_name = 'ROBERT'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'STANNIS'), 
			(SELECT id FROM Characters WHERE F_name = 'RENLY'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'STANNIS'), 
			(SELECT id FROM Characters WHERE F_name = 'MELISANDRE'), 
			(SELECT id FROM Connection_Type WHERE Description = 'LOVER')),
		((SELECT id FROM Characters WHERE F_name = 'STANNIS'), 
			(SELECT id FROM Characters WHERE F_name = 'DAVOS'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),

		((SELECT id FROM Characters WHERE F_name = 'RENLY'), 
			(SELECT id FROM Characters WHERE F_name = 'MARGAERY'), 
			(SELECT id FROM Connection_Type WHERE Description = 'HUSBAND')),
		((SELECT id FROM Characters WHERE F_name = 'RENLY'), 
			(SELECT id FROM Characters WHERE F_name = 'STANNIS'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'RENLY'), 
			(SELECT id FROM Characters WHERE F_name = 'ROBERT'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'RENLY'), 
			(SELECT id FROM Characters WHERE F_name = 'LORAS'), 
			(SELECT id FROM Connection_Type WHERE Description = 'LOVER')),
		((SELECT id FROM Characters WHERE F_name = 'RENLY'), 
			(SELECT id FROM Characters WHERE F_name = 'BRIENNE'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),

		((SELECT id FROM Characters WHERE F_name = 'MELISANDRE'), 
			(SELECT id FROM Characters WHERE F_name = 'STANNIS'), 
			(SELECT id FROM Connection_Type WHERE Description = 'LOVER')),

		((SELECT id FROM Characters WHERE F_name = 'DAVOS'), 
			(SELECT id FROM Characters WHERE F_name = 'STANNIS'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		((SELECT id FROM Characters WHERE F_name = 'DAVOS'), 
			(SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),

		((SELECT id FROM Characters WHERE F_name = 'BRIENNE'), 
			(SELECT id FROM Characters WHERE F_name = 'RENLY'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		((SELECT id FROM Characters WHERE F_name = 'BRIENNE'), 
			(SELECT id FROM Characters WHERE F_name = 'CATELYN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		((SELECT id FROM Characters WHERE F_name = 'BRIENNE'), 
			(SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		((SELECT id FROM Characters WHERE F_name = 'BRIENNE'), 
			(SELECT id FROM Characters WHERE F_name = 'STANNIS'), 
			(SELECT id FROM Connection_Type WHERE Description = 'KILLER')),


		((SELECT id FROM Characters WHERE F_name = 'PETYR'), 
			(SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		
		((SELECT id FROM Characters WHERE F_name = 'EURON'), 
			(SELECT id FROM Characters WHERE F_name = 'BALON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'EURON'), 
			(SELECT id FROM Characters WHERE F_name = 'THEON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'UNCLE')),
		((SELECT id FROM Characters WHERE F_name = 'EURON'), 
			(SELECT id FROM Characters WHERE F_name = 'YARA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'UNCLE')),
		((SELECT id FROM Characters WHERE F_name = 'EURON'), 
			(SELECT id FROM Characters WHERE F_name = 'BALON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'KILLER')),

		((SELECT id FROM Characters WHERE F_name = 'BALON'), 
			(SELECT id FROM Characters WHERE F_name = 'EURON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'BALON'), 
			(SELECT id FROM Characters WHERE F_name = 'THEON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'FATHER')),
		((SELECT id FROM Characters WHERE F_name = 'BALON'), 
			(SELECT id FROM Characters WHERE F_name = 'YARA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'FATHER')),

		((SELECT id FROM Characters WHERE F_name = 'THEON'), 
			(SELECT id FROM Characters WHERE F_name = 'EURON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'NEPHEW')),
		((SELECT id FROM Characters WHERE F_name = 'THEON'), 
			(SELECT id FROM Characters WHERE F_name = 'BALON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SON')),
		((SELECT id FROM Characters WHERE F_name = 'THEON'), 
			(SELECT id FROM Characters WHERE F_name = 'YARA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'THEON'), 
			(SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),


		((SELECT id FROM Characters WHERE F_name = 'ROOSE'), 
			(SELECT id FROM Characters WHERE F_name = 'RAMSAY'), 
			(SELECT id FROM Connection_Type WHERE Description = 'FATHER')),

		((SELECT id FROM Characters WHERE F_name = 'RAMSAY'), 
			(SELECT id FROM Characters WHERE F_name = 'ROOSE'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SON')),
		((SELECT id FROM Characters WHERE F_name = 'RAMSAY'), 
			(SELECT id FROM Characters WHERE F_name = 'ROOSE'), 
			(SELECT id FROM Connection_Type WHERE Description = 'KILLER')),
		((SELECT id FROM Characters WHERE F_name = 'RAMSAY'), 
			(SELECT id FROM Characters WHERE F_name = 'SANSA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'HUSBAND')),


		((SELECT id FROM Characters WHERE F_name = 'SAMWELL'), 
			(SELECT id FROM Characters WHERE F_name = 'GILLY'), 
			(SELECT id FROM Connection_Type WHERE Description = 'LOVER')),
		((SELECT id FROM Characters WHERE F_name = 'SAMWELL'), 
			(SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),

		((SELECT id FROM Characters WHERE F_name = 'GILLY'), 
			(SELECT id FROM Characters WHERE F_name = 'SAMWELL'), 
			(SELECT id FROM Connection_Type WHERE Description = 'LOVER')),


		((SELECT id FROM Characters WHERE F_name = 'DAENERYS'), 
			(SELECT id FROM Characters WHERE F_name = 'RHAEGAR'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SISTER')),
		((SELECT id FROM Characters WHERE F_name = 'DAENERYS'), 
			(SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'AUNT')),
		((SELECT id FROM Characters WHERE F_name = 'DAENERYS'), 
			(SELECT id FROM Characters WHERE F_name = 'MISSANDEI'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		((SELECT id FROM Characters WHERE F_name = 'DAENERYS'), 
			(SELECT id FROM Characters WHERE F_name = 'GREY'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		((SELECT id FROM Characters WHERE F_name = 'DAENERYS'), 
			(SELECT id FROM Characters WHERE F_name = 'DAARIO'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		((SELECT id FROM Characters WHERE F_name = 'DAENERYS'), 
			(SELECT id FROM Characters WHERE F_name = 'DAARIO'), 
			(SELECT id FROM Connection_Type WHERE Description = 'LOVER')),
		((SELECT id FROM Characters WHERE F_name = 'DAENERYS'), 
			(SELECT id FROM Characters WHERE F_name = 'JORAH'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		((SELECT id FROM Characters WHERE F_name = 'DAENERYS'), 
			(SELECT id FROM Characters WHERE F_name = 'KHAL'), 
			(SELECT id FROM Connection_Type WHERE Description = 'WIFE')),
		((SELECT id FROM Characters WHERE F_name = 'DAENERYS'), 
			(SELECT id FROM Characters WHERE F_name = 'TYRION'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		
		((SELECT id FROM Characters WHERE F_name = 'RHAEGAR'), 
			(SELECT id FROM Characters WHERE F_name = 'DAENERYS'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'RHAEGAR'), 
			(SELECT id FROM Characters WHERE F_name = 'JON'), 
			(SELECT id FROM Connection_Type WHERE Description = 'FATHER')),
		((SELECT id FROM Characters WHERE F_name = 'RHAEGAR'), 
			(SELECT id FROM Characters WHERE F_name = 'ELIA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'HUSBAND')),
		
		((SELECT id FROM Characters WHERE F_name = 'MISSANDEI'), 
			(SELECT id FROM Characters WHERE F_name = 'DAENERYS'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		((SELECT id FROM Characters WHERE F_name = 'MISSANDEI'), 
			(SELECT id FROM Characters WHERE F_name = 'GREY'), 
			(SELECT id FROM Connection_Type WHERE Description = 'LOVER')),

		((SELECT id FROM Characters WHERE F_name = 'GREY'), 
			(SELECT id FROM Characters WHERE F_name = 'DAENERYS'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		((SELECT id FROM Characters WHERE F_name = 'GREY'), 
			(SELECT id FROM Characters WHERE F_name = 'MISSANDEI'), 
			(SELECT id FROM Connection_Type WHERE Description = 'LOVER')),

		((SELECT id FROM Characters WHERE F_name = 'DAARIO'), 
			(SELECT id FROM Characters WHERE F_name = 'DAENERYS'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),
		((SELECT id FROM Characters WHERE F_name = 'DAARIO'), 
			(SELECT id FROM Characters WHERE F_name = 'DAENERYS'), 
			(SELECT id FROM Connection_Type WHERE Description = 'LOVER')),

		((SELECT id FROM Characters WHERE F_name = 'JORAH'), 
			(SELECT id FROM Characters WHERE F_name = 'DAENERYS'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),

		((SELECT id FROM Characters WHERE F_name = 'KHAL'), 
			(SELECT id FROM Characters WHERE F_name = 'DAENERYS'), 
			(SELECT id FROM Connection_Type WHERE Description = 'HUSBAND')),


		((SELECT id FROM Characters WHERE F_name = 'ELIA'), 
			(SELECT id FROM Characters WHERE F_name = 'RHAEGAR'), 
			(SELECT id FROM Connection_Type WHERE Description = 'WIFE')),
		((SELECT id FROM Characters WHERE F_name = 'ELIA'), 
			(SELECT id FROM Characters WHERE F_name = 'DORAN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SISTER')),
		((SELECT id FROM Characters WHERE F_name = 'ELIA'), 
			(SELECT id FROM Characters WHERE F_name = 'OBERYN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SISTER')),
		((SELECT id FROM Characters WHERE F_name = 'TRYSTANE'), 
			(SELECT id FROM Characters WHERE F_name = 'OBERYN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'AUNT')),

		((SELECT id FROM Characters WHERE F_name = 'DORAN'), 
			(SELECT id FROM Characters WHERE F_name = 'ELIA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'DORAN'), 
			(SELECT id FROM Characters WHERE F_name = 'OBERYN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'DORAN'), 
			(SELECT id FROM Characters WHERE F_name = 'TRYSTANE'), 
			(SELECT id FROM Connection_Type WHERE Description = 'FATHER')),

		((SELECT id FROM Characters WHERE F_name = 'OBERYN'), 
			(SELECT id FROM Characters WHERE F_name = 'ELIA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'OBERYN'), 
			(SELECT id FROM Characters WHERE F_name = 'DORAN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'OBERYN'), 
			(SELECT id FROM Characters WHERE F_name = 'TRYSTANE'), 
			(SELECT id FROM Connection_Type WHERE Description = 'UNCLE')),
		((SELECT id FROM Characters WHERE F_name = 'OBERYN'), 
			(SELECT id FROM Characters WHERE F_name = 'ELLARIA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'LOVER')),

		((SELECT id FROM Characters WHERE F_name = 'TRYSTANE'), 
			(SELECT id FROM Characters WHERE F_name = 'DORAN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'SON')),
		((SELECT id FROM Characters WHERE F_name = 'TRYSTANE'), 
			(SELECT id FROM Characters WHERE F_name = 'ELIA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'NEPHEW')),
		((SELECT id FROM Characters WHERE F_name = 'TRYSTANE'), 
			(SELECT id FROM Characters WHERE F_name = 'OBERYN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'NEPHEW')),
		((SELECT id FROM Characters WHERE F_name = 'TRYSTANE'), 
			(SELECT id FROM Characters WHERE F_name = 'MYRCELLA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'LOVER')),


		((SELECT id FROM Characters WHERE F_name = 'ELLARIA'), 
			(SELECT id FROM Characters WHERE F_name = 'OBERYN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'LOVER')),
		((SELECT id FROM Characters WHERE F_name = 'ELLARIA'), 
			(SELECT id FROM Characters WHERE F_name = 'DORAN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'KILLER')),
		((SELECT id FROM Characters WHERE F_name = 'ELLARIA'), 
			(SELECT id FROM Characters WHERE F_name = 'MYRCELLA'), 
			(SELECT id FROM Connection_Type WHERE Description = 'KILLER')),
		((SELECT id FROM Characters WHERE F_name = 'ELLARIA'), 
			(SELECT id FROM Characters WHERE F_name = 'TRYSTANE'), 
			(SELECT id FROM Connection_Type WHERE Description = 'KILLER')),


		((SELECT id FROM Characters WHERE F_name = 'GREGOR'), 
			(SELECT id FROM Characters WHERE F_name = 'SANDOR'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),
		((SELECT id FROM Characters WHERE F_name = 'GREGOR'), 
			(SELECT id FROM Characters WHERE F_name = 'OBERYN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'KILLER')),
		((SELECT id FROM Characters WHERE F_name = 'GREGOR'), 
			(SELECT id FROM Characters WHERE F_name = 'CERSEI'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY')),

		((SELECT id FROM Characters WHERE F_name = 'SANDOR'), 
			(SELECT id FROM Characters WHERE F_name = 'GREGOR'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),


		((SELECT id FROM Characters WHERE F_name = 'EDMURE'), 
			(SELECT id FROM Characters WHERE F_name = 'CATELYN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'BROTHER')),

		((SELECT id FROM Characters WHERE F_name = 'HODOR'), 
			(SELECT id FROM Characters WHERE F_name = 'BRAN'), 
			(SELECT id FROM Connection_Type WHERE Description = 'ALLY'));
