DROP TABLE IF EXISTS `Region`;

-- Create Region Table
CREATE TABLE Region (
	id INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(255) NOT NULL UNIQUE,
	Continent VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
) ENGINE=InnoDB;