#ifndef GAME_ELEMENTS_OBJ_HPP
#define GAME_ELEMENTS_OBJ_HPP

vector<string> objLongDesc = {
							"Trevor's Wallet, inside is Trevor's learner's permit , a few dollars, and a bunch of quarters...perhaps there is a local arcade he frequents.",
							"You see a small, glass vial with some residue at the bottom.",
							"this is a very looooooooooooooong description for this object -> loveNote",
							"You see an Autopsy Report. In it are details regarding the the ME Frank's findings, including a lethal dosage of \na drug.",
							"The Pharmacy Receipt details Bobby's prescription, including when the last refill as, and the fact that Beth picked it \nup.",
							"Bobby's old, empty pill bottle. It explcitly states: DO NOT TAKE WITH ALCOHOL.",
							"You see a stunning, 5 carat diamond ring. It glimmers in the light...so beautiful, so entrancing. An hour later you \nsnap to.",
							"Bobby's phone, unlocked by the local Police Department. It's rather old, a Nokia. You wonder if it has 'Snake' on it...",
							"Your trusty, handy dandy lockpick. It's worn but functional, having been used countless times.",
							"Your flashlight, a small, black one you got from police surplus. It's hardy.",
							"The suspect list, a list of suspects.",
							"The bar trash can, grey with a bag liner. It's half full of rubbish.",
							"A very odd taxidermied creature. Clearly from more than one animal, and then some.",
							"A standard bar chair, wooden and tall.",
							"A standard bar table to go with the chairs. Wooden and worn, with various phrases and numbers carved across it.",
							"The booths all have large backs, making them seem somewhat enclosed. The one with police tape is clearly where Bobby \ndied. It seems any evidence that existed was already removed by the local police.",
							"Just some rags used to clean up messes and the occasional drunken induced vomit.",
							"The bar shelving is populated with various spirits, all of which look more half empty than half full.",
							"You see Bobby's body, it has been undressed and lain on its back, a large blanket covering most of it.",
							"The ME's desk, complete with folders, papers, and notes.",
							"The coolers reach from floor to near ceiling, stocked full of various drinks such as juices and alcoholic beverages.",
							"The freezers reach from floor to near ceiling, stocked full of frozen foods such as meats, vegetables, t.v. dinners, \nand ice creams.",
							"The shelves are stocked with all kinds of home use items, from dry and packaged foods to lightbulbs, glue, and staples.",
							"The bulletin board, which for a small town is expectedly bare. The only thing up aside from stuff about Bobby is a flier\nfor a potluck this Sunday.",
							"The break table has metal legs with a thin hard plastic top. Scattered about are various condiments and to a lack of \nsurprise, a box of doughnuts.",
							"You see Beth's door, it is white with a peephole. A sign on it welcomes those who stand before it.",
							"A cute garden, comprised mostly of flowers with a section at one end for herbs. You lose yourself for a few minutes as \nyou watch a ladybug traverse a couple of leaves.",
							"You see a modern looking table, with three legs that combine as they meet at the base of the top. It has a cultured \nmarble surface.",
							"It is a small box, made of sturdy cardboard covered in some tough yet stylish fabric. Probably from y-Kea.",
							"You see a white, sleek comforter neatly tucked in with a few large white pillows and one circular accent pillow in the \ncenter. It's mauve.",
							"The dresser stands against the wall, nothing spectacular about it as there is nothing on top. Opening the drawers you see neatly folder clothes, many white with some earth tones.",
							"You see a suspiciuos looking garden gnome with a red hat, white tunic, and no pants. Why is it suspicious? You swear it\nis looking right at you...",
							"Plastic pink flamingos, the kind every american at some point in their life has seen amidst a neighbor's lawn setup. \nThese looked weathered, however, as though they have been there for years.",
							"The door looks weathered, with one giant sunflower painted on it.",
							"This t.v. looks quite old, with a big back to it. You estimate its age at 15 - 20 years.",
							"You see a large, knit rug in the shape of a sunflower. It looks somewhat heavy. You can't imagine Claire cleans under \nit. You flip and edge over slightly to see it is clean. You stand corrected.",
							"The dresser is brown and old, just like everything else. The knobs have been painted to look like individual sunflowers.\nYou search inside to see an iron key.",
							"The pictures across the top show some older people in color, with some young versions of them in black and white. \nPerhaps her parents.",
							"You see what looks like some sort of shrine. It is covered in photos of Beth, with some group photos with faces crossed out\nand in photos including Bobby, she has clearly pasted her own face over his. Furthermore, you see what looks \nlike a lock of Beth's hair wrapped in ribbon. You've clearly stumbled upon Claire's obsessive secret. And right smack dab in the \nmiddle is an empty pill bottle. The bottle just might be the evidene you need to make an arrest!",
							"You see cans of food, stockpiled for a fear never realized during the cold war. Half of it is Spam.",
							"You see many jugs of water with labels from a time since passed. It still looks clear, but looks can be deceiving.",
							"You see a 1966 Pontiac GTO coupe with a Montero Red exterior paint. It looks incredible, as though it came fresh off the\nline. You scope out the interior to see it is completely empty save the registration and insurance. He lets nothing in\nhere that shouldn't belong.",
							"You see a few scattered tool chests, vibrant red, full of tools that look like they get lots of use. You can see the \nlevel of dedication Bobby had for his car.",
							"Rags, soiled in greese and oil. They seem worn and tattered from overuse.",
							"The door is in a small screen enclosure. It is red, and in fairly good condition save a few chips of paint and a scratch\nhere and there.",
							"You see a newer, 60inch flatscreen tv. It's off, but the temptation to test the color quality is tempting. It's made by\nHamsung.",
							"You see various cinema posters for movies such as Pulp Non-Fiction, The Small Lebowski, and The Boonies.",
							"You see Excalibur. A '64 Fender Stratocaster in classic white with triple single coil pickups and a whammy bar", // Wayne's World Quote
							"You see a small, pressed wood desk with a granite veneer. On it are some papers. You shuffle through to find a loan \napplication that Bobby was in the works with to deal with his debt issue.",
							"The framed jersey is gold and black with a fleur-de-lis on it. It says 'Brees' on it.",
							"You see a large computer tower with an Alien symbol on it connected to 3 large monitors. Game much?",
							"Bobby's bed is both black and gold in color, with a large fleur-de-lis across the middle. The pillows are in the shape \nof footballs.",
							"The dresser is pressed wood with a granite veneer, just like the desk in the office. You don't recall seeing a y-Kea on your\nway in but this is surely from there. Inside are various articles of clothing partially folded, well, less folded and\nmore stuffed in.",
							"You look about the bookshelf. It is more of a trophy shelf, actually. Most of it in various high school athletics, \nnamely football. There are a few, near the bottom, for tap dancing. Seems like Bobby was well rounded in the skills \ndepartment.",
							"Bobby's nightstand, granite veneer on pressed wood. Inside are some random things you'd expect such as cough drops and \nlots of change. You see a chapter book titled 'Sense and Sensibility'. Seems like Bobby had a sensitive, intellectual \nside. Well done, Bobby... well done.",
							"You see metal tube chimes dangling from a wooden disc. They ring rather loudly, but a tune so relaxing you suddenly \nrealize you've been standing there for the better part of 10 minutes.",
							"A stone birdbath. It doesn't look like it is hooked up to a water source, but the lack of rain this month and the \nfact that it's filled with water indicates Sam cares for the little birdies. How sweet.",
							"You see a cat. It is orange. You aren't sure, but even though the cat seems to not care about your presence...it \nequally seems to be wholly fixated on you. For a second it glances at you...possibly confirming the latter. It licks \nitself for a moment, glances at you again, then sprawls across the ground as though it is winning at life.",		
							"The door is large and blue. You wonder, if it's larger on the inside than the outside...",	
							"The brown seude couches are actually much older and originally yellow, the brown seude being a duvet cover. A nice, \ncheap way to update any decor.",	
							"The glass table has chips at the edges, the whole of it resting atop a metal frame. The empty beer bottles are many.",	
							"The newspapers seem to all be originals from the time of their print, the value of them escapes you. They are all \npolitically charged milestones in America's transition from an industrial based economy to that of a service \nbased economy.",	
							"The entertainment center contains compartment housing various items from movies to video games. One cubby stands out as\nempty save 5 copies of 'The Catcher in the Rye'.",	
							"The bed is a hot mess, with snacks and newspapers scattered about. He must do this often, as the once white sheets are \nstained in newspaper ink. You see see a french fry sticking out from under a pillow, but oddly no fast food bags.",	
							"The newspapers are newer, with subjects surrounding political scandall. MANY words are either underlined or circled. \nEither he has a beautiful mind, or is a few fries short of a Happy Meal. Maybe that fry on the bed...",
							"The dresser is very plain looking. You open the drawers to see it half filled with clothes and half filled with \nnewspapers. You can tell he has already taken a pen to them.",
							"You see some figurines of things out of a Science Fiction movie. Robots and Aliens, who does't love those? The robot \nseemed pre-made, but the alien model you can tell was glued together by someone. You see near it is a candle...\nmaybe not the best idea, Sam.",	
							"You see a cornucopia of medications for Sam, much if it related to anxiety and stress, as well as sleep aides. Poor guy.",	
							"You see many snack bags on the bed, most of them over half empty. Chips, Pretzels, Gummies, and more. You notice not one\nlick of it is a vegetable. You should have a talk with Sam.",		
							"Sam's desk is very simple and small, more like a table with a chair than an actual desk. It does have a drawer so you \nguess it qualifies. On it is a laptop. In the drawer you see a small piece of paper with some numbers on it. \nPerhaps a code?",		
							"You see Sam's laptop, a Hamsung. You take it out of sleep to be met with a password protected screen. Hmm, perhaps \nthere is a code around here you can use.",
							"The truck looks like it is from the 60's, except its appreance would suggest tiem got the better of it. The shell is \nrusted throughout, the inside tattered and barren. You sneak a peek under the hood, just to see no engine block.",
							"A nice, Harley Davidson motorcycle, matte black. The paniers on the side are empty, much like the stare from the jolly \nroger flag waving about the bike.",
							"You see a door, and it would be rather inviting if it weren't for the sign stating 'Tresspassers Will Be Shot'. \nNot sure this Moose character is going to be cooperative.",
							"The old couch has a camo-themed style. There are no pillows, but there are a few coozies piled into a corner.",
							"A large, natural wooden table is before you, with various papers scattered across. Moose and Sam are sitting at it.",
							"The papers are scattered before Moose and Sam, so you dare not get too close. From a distance, it appears they are \nscribblings of Horse names and monetary values associated with them. You wonder, if Moose may be some sort of bookie.",
							"Heck yeah, a waterbed! I mean, do they still make these things!? Er, I mean...ug, You see Moose's waterbed, covered in \nlarge fur blankets. They look real. You might say they feel real if you knew what a real bear felt like. \nYou push against the end to watch it ripple and sway about. Inside you, the inner child is dying to plop on.",
							"Fur blanket of various animls. A bear, wolf, fox, some racoons, and a squirrel? You know this because each blanket \nstill has a HEAD.",
							"A wooden table that looks like it has some burn marks and scratches on it. Probably, like most things around here, \nisn't well maintained and treated rather poorly.",
							"A ragged old dresser, with some missing drawers. The present ones are filled with crumpled up clothes and a few pouches\nof chewing tobacco. This game does not condone tobacco use.",
							"The beer cans are stacked in a pyramid. The brand has a logo indicating that at one point, they won a blue ribbon. \nSounds quality.",
							"There are many articles of clothing scattered about the floor. You question their cleanliness, and opt out of touching \nthem. Kicking them around reveals nothing underneath save some burn marks in the carpet.",
							"A curious chicken, no doubt. Its eyes beady, its head bobbing about quickly. You know you could get closer for a better\nexamination, but deep down you are scared.",
							"A plain, bland door. Nothing exciting to talk about except that you have nothing to talk about when talking about it.",
							"You see a chaise sectional, with blankets on it. It looks like someone lounges here a lot. It's grey.",
							"You see a metal birdcage hanging from a hook in the ceiling. The cage is large, yet has one cockatiel in it. Maybe it \nonce had a mate...maybe...",
							"You see a cockatiel. It is white with yellow plumage atop its head that springs up periodically, as well as little \norange dots on its 'cheeks'. Adorable.",
							"You see a wooden kitchen table, with a few bowls and boxes of cereal atop. Most of the cereals are sugary and diabetes \ninvoking. Some papers are on it.",
							"You see some papers that are bills for utilites. A piece of paper sticking out from under a bowl catches your eye, but upon closer examination see it is a note: 'Trevor, don't you dare touch my drumset while I'm gone'",
							"You see two beds. One must be Trent's, and the other that Trevor is on is, well...Trevor's.",
							"You see a large dresser with nothing special atop it. You ask Trevor to search the drawers, and he nods. He points out \nthat they share the dresser, and that the right half is his, the left is Trent's. You find nothing significant.",
							"You see posters of Heavy Metal and Hair Bands. ",
							"A drumset, black in color with white tops. It looks like the tops get lots of use and should be replaced. It might be \nbest if you didn't touch it...",
							"An acoustic, 6-string guitar signed by some name you can't make out. It has a blue pic woven into the strings at the \ntop of the neck.",
							"You see a large, metal, hidden door. At its side is an openeing for what looks like a key.",
							"You see booze. Not really much more can be said about it. Did I mention it was Generic?",
							"You see an alphanumeric code, probably used to unlock something digital.",
							"You see various emails from Sam to Beth, declaring his love and desire for Beth to leave Bobby for him.",
							"You see a loan application Bobby had filled out to deal with his debt issue. He was clearly working to resolve it. \nTaking this should help show he wanted to live.",
							"A blanket warrant to legally search the homes in town. Kind of convenient, don't you think?",
							"The bed looks like a garden theme, with a brown comforter and sunflower pillows. You look under the comforter to see \nsunflower themed sheets. You feel the need to look under the bed, to which you find a pile of dirt. Too far, Claire, \ntoo far.",
							"A panel that blends in with the wall was craftily made to look seamless. Nice one.",
							"You see an empty bottle with Bobby's name on it. You compare it to the receipt to see it is the exact bottle Beth had \npicked up last from the Pharmacy.",
							"You see an iron key, a somewhat old looking one at that. To what it goes to you can only ponder."
						};	
									
#endif