#ifndef GAME_ELEMENTS_HPP
#define GAME_ELEMENTS_HPP

#include "game_elements_room.hpp"   //room descriptions
#include "game_elements_char.hpp"   //character descriptions
#include "game_elements_obj.hpp"   //object descriptions

//enums of rooms , characters and objects
enum roomList{
				FAKE,
				BAR, 
				HIDDEN,
				POLICE,
				MORGUE,
				PHARMACY,
				BOBLR,
				BOBOFF,	
				BOBBR,	
				BOBFP,
				CLAIRELR,	
				CLAIREBUNK,
				CLAIREBR,
				CLAIREFP,
				BETHLR,
				BETHBR,
				BETHFP,
				SAMLR,
				SAMBR,
				SAMFP,
				TRENTLR,
				TRENTBR,
				TRENTFP,
				MOOSELR,
				MOOSEBR,
				MOOSEFP,
			NUM_OF_ROOMS	
		};

enum charList{
				BETH,
				CLAIRE,
				SAM,
				FRANK,
				TRENT,
				TREVOR,
				MOOSE,
				ABE,
				RORY,
			NUM_OF_CHARS
		};


enum objList{
				TREVWALLET,
				VIAL,
				LOVENOTE,
				AUTOPSY,
				RECEIPT,
				PILLBOTTLE,
				RING,
				BOBPHONE,
				LOCKPICK,
				LIGHT,
				SUSPECTLIST,
				BARTRASH,
				BARCREATURE,
				BARCHAIR,
				BARTABLE,
				BARBOOTH,
				BARRAGS,
				BARSHELVES,
				BOBBODY,
				MORGUEDESK,
				PHARMCOOLERS,
				PHARMFREEZERS,
				PHARMSHELVES,
				POLBULLETIN,
				POLTABLE,
				BETHDOOR,
				BETHGARDEN,
				BETHTABLE,
				BETHBOX,
				BETHBED,
				BETHDRESSER,
				CLAIREGNOME,
				CLAIREFLAMINGOS,
				CLAIREDOOR,
				CLAIRETV,
				CLAIRERUG,
				CLAIREDRESSER,
				CLAIREPICS,
				CLAIRESHRINE,
				CLAIRECANS,
				CLAIREWATER,
				BOBCAR,
				BOBCHESTS,
				BOBRAGS,
				BOBDOOR,
				BOBTV,
				BOBPOSTERS,
				BOBGUITAR,
				BOBDESK,
				BOBJERSEY,
				BOBCOMPUTER,
				BOBBED,
				BOBDRESSER,
				BOBBOOKSHELF,
				BOBNIGHTSTAND,	
				SAMCHIMES,
				SAMBIRDBATH,
				SAMCAT,		
				SAMDOOR,	
				SAMCOUCH,	
				SAMTABLE,	
				SAMPAPERLR,	
				SAMENTCENTER,	
				SAMBED,	
				SAMPAPERBR,
				SAMDRESSER,
				SAMFIGURINES,	
				SAMMEDICINE,	
				SAMSNACKS,		
				SAMDESK,		
				SAMLAPTOP,	
				MOOSETRUCK,
				MOOSEMOTORCYCLE,
				MOOSEDOOR,
				MOOSECOUCH,
				MOOSETABLELR,
				MOOSEPAPERS,
				MOOSEWATERBED,
				MOOSEBLANKETS,
				MOOSETABLEBR,
				MOOSEDRESSER,
				MOOSEBEERCANS,
				MOOSECLOTHES,
				TRENTCHICKEN,
				TRENTDOOR,
				TRENTCOUCH,
				TRENTBIRDCAGE,
				TRENTBIRD,
				TRENTTABLE,
				TRENTPAPERS,
				TRENTBED,
				TRENTDRESSER,
				TRENTPOSTERS,
				TRENTDRUMS,
				TRENTGUITAR,
				BUNKDOOR,
				BOOZE,
				SAMCODE,
				SAMEMAILS,
				BOBLOAN,
				WARRANT,
				CLAIREBED,
				HIDDENDOOR,
				EMPTYBOTTLE,
				BUNKKEY,
			NUM_OF_OBJS
        };		

		
//string names of rooms, characters and objects		
vector<string> roomName = {
							"fake",			// "Fake" placeholder,
							"bar",          // "Bar",                       
							"hidden",       // "Hidden Room",               
							"police",       // "Police Station",            
							"morgue",       // "Morgue",                    
							"pharmacy",     // "Pharmacy",                  
							"bobLR",        // "Bobby Living Room",         
							"bobOFF",       // "Bobby Office",              
							"bobBR",        // "Bobby Bedroom",             
							"bobFP",        // "Bobby Front Porch",         
							"claireLR",     // "Claire Living Room",        
							"claireBUNK",   // "Claire Bunker",             
							"claireBR",     // "Claire Bedroom",            
							"claireFP",     // "Claire Front Porch",        
							"bethLR",       // "Beth Living Room",          
							"bethBR",       // "Beth Bedroom",              
							"bethFP",       // "Beth Front Porch",          
							"samLR",        // "Sam Living Room",           
							"samBR",        // "Sam Bedroom",               
							"samFP",        // "Sam Front Porch",           
							"trentLR",      // "Trent Living Room",         
							"trentBR",      // "Trent Bedroom",             
							"trentFP",      // "Trent Front Porch",         
							"mooseLR",      // "Moose Living Room",         
							"mooseBR",      // "Moose Bedroom",             
							"mooseFP"       // "Moose Front Porch"			
						};
						
vector<string> roomDisplayName = {
							"Fake", 		// placeholder
							"The Bar",                       
							"The Hidden Room",               
							"The Police Station",            
							"The Morgue",                    
							"The Pharmacy",                  
							"Bobby's Living Room",         
							"Bobby's Office",              
							"Bobby's Bedroom",             
							"Bobby's Front Porch",         
							"Claire's Living Room",        
							"Claire's Bunker",             
							"Claire's Bedroom",            
							"Claire's Front Porch",        
							"Beth's Living Room",          
							"Beth's Bedroom",              
							"Beth's Front Porch",          
							"Sam's Living Room",           
							"Sam's Bedroom",               
							"Sam's Front Porch",           
							"Trent's Living Room",         
							"Trent's Bedroom",             
							"Trent's Front Porch",         
							"Moose's Living Room",         
							"Moose's Bedroom",             
							"Moose's Front Porch"			
						};
						
vector<string> characterName = {
							"beth",
							"claire",
							"sam",
							"frank",
							"trent",
							"trevor",
							"moose",
							"abe",
							"rory"	
						};			

vector<string> charDisplayName = {
							"Beth",
							"Claire",
							"Sam",
							"Frank",
							"Trent",
							"Trevor",
							"Moose",
							"Abe",
							"Rory"	
						};						
		
vector<string> objName = {
							"trevWallet",
							"vial",
							"loveNote",
							"autopsy",
							"receipt",
							"pillBottle",
							"ring",
							"bobPhone",
							"lockpick",
							"light",
							"suspectList",         
							"trash",//"barTrash",
							"creature",//"barCreature",
							"chair",//"barChair",
							"table",//"barTable",
							"booth",//"barBooth",
							"rags",//"barRags",
							"shelves",//"barShelves",
							"body",//"bobBody",
							"desk",//"morgueDesk",
							"coolers",//"pharmCoolers",
							"freezers",//"pharmFreezers",
							"shelves",//"pharmShelves",
							"bulletin",//"polBulletin",
							"table",//"polTable",
							"door",//"bethDoor",
							"garden",//"bethGarden",
							"table",//"bethTable",
							"box",//"bethBox",
							"bed",//"bethBed",
							"dresser",//"bethDresser",
							"gnome",//"claireGnome",
							"flamingos",//"claireFlamingos",
							"door",//"claireDoor",
							"tv",//"claireTV",
							"rug",//"claireRug",
							"dresser",//"claireDresser",
							"pictures",//"clairePics",
							"shrine",//"claireShrine",
							"beer",//"claireCans",
							"water",//"claireWater",     
							"car",//"bobCar",
							"chests",//"bobChests",
							"rags",//"bobRags",
							"door",//"bobDoor",
							"tv",//"bobTV",
							"posters",//"bobPosters",
							"guitar",//"bobGuitar",
							"desk",//"bobDesk",
							"jersey",//"bobJersey",
							"computer",//"bobComputer",
							"bed",//"bobBed",
							"dresser",//"bobDresser",
							"bookshelf",//"bobBookshelf",
							"nightstand",//"bobNightstand",
							"chimes",//"samChimes",
							"birdbath",//"samBirdbath",
							"cat",//"samCat",		
							"door",//"samDoor",	
							"couch",//"samCouch",	
							"table",//"samTable",	
							"newspapers",//"samPaperLR",	
							"entertainment",//"samEntCenter",	
							"bed",//"samBed",	
							"newspapers",//"samPaperBR",
							"dresser",//"samDresser",
							"figurines",//"samFigurines",	
							"medicine",//"samMedicine",	
							"snacks",//"samSnacks",		
							"desk",//"samDesk",		
							"laptop",//"samLaptop",
							"truck",//"mooseTruck",
							"motorcycle",//"mooseMotorcycle",
							"door",//"mooseDoor",
							"couch",//"mooseCouch",
							"table",//"mooseTableLR",
							"papers",//"moosePapers",
							"waterbed",//"mooseWaterbed",
							"blankets",//"mooseBlankets",
							"table",//"mooseTableBR",
							"dresser",//"mooseDresser",
							"beer",//"mooseBeerCans",
							"clothes",//"mooseClothes",
							"chicken",//"trentChicken",
							"door",//"trentDoor",
							"couch",//"trentCouch",
							"birdcage",//"trentBirdcage",
							"bird",//"trentBird",
							"table",//"trentTable",
							"papers",//"trentPapers",
							"bed",//"trentBed",
							"dresser",//"trentDresser",
							"posters",//trentPosters",
							"drums",//"trentDrums",
							"guitar",//"trentGuitar",
							"door",//"bunkDoor",
							"beer",
							"code",
							"emails",
							"loan",
							"warrant",
							"bed", // "claireBed"
							"door",
							"pillBottle",
							"key"
						};
						
vector<string> objDisplayName = {
							"Trevor's Wallet",
							"Vial",
							"Love Note",
							"Autopsy Report",
							"Pharmacy Receipt",
							"Pill Bottle",
							"Engagement Ring",
							"Bobby's Phone",
							"Lockpick",
							"Flashlight",
							"Suspect List",
							"Trash",
							"Stuffed Creature",
							"Chair",
							"Table",
							"Booth",
							"Rags",
							"Shelves",
							"Bobby's Body",
							"Desk",
							"Coolers",
							"Freezers",
							"Shelves",
							"Bulletin Board",
							"Table",
							"Beth's Front Door",
							"Garden",
							"Table",
							"Box",
							"Bed",
							"Dresser",
							"Gnome",
							"Flamingos",
							"Claire's Front Door",
							"TV",
							"Rug",
							"Dresser",
							"Photographs",
							"Shrine",
							"Cans",
							"Water",
							"Car",
							"Chests",
							"Rags",
							"Bob's Front Door",
							"TV",
							"Posters",
							"Guitar",
							"Desk",
							"Jersey",
							"Computer",
							"Bed",
							"Dresser",
							"Bookshelf",
							"Nightstand",
							"Chimes",
							"Birdbath",
							"Cat",		
							"Sam's Front Door",	
							"Couch",	
							"Table",	
							"Newspaper",	
							"Entertainment Center",	
							"Bed",	
							"Newspapers",
							"Dresser",
							"Model Figurines",	
							"Medicine",	
							"Snacks",		
							"Desk",		
							"Laptop",
							"Truck",
							"Motorcycle",
							"Moose's Front Door",
							"Couch",
							"Table",
							"Paper",
							"Waterbed",
							"Blankets",
							"Table",
							"Dresser",
							"Beer Cans",
							"Clothes",
							"Chicken",
							"Trent's Front Door",
							"Couch",
							"Birdcage",
							"Bird",
							"Table",
							"Papers",
							"Beds",
							"Dresser",
							"Posters",
							"Drum Set",
							"Guitar",
							"Bunker Door",
							"Booze",
							"Code",
							"Emails",
							"Loan Application",
							"Search Warrant",
							"Bed",
							"Hidden Room Door",
							"Empty Pill Bottle",
							"Iron Key"
						};

vector<bool> objLockedStatus = {
							false,		// "Trevor's Wallet",
							false,		// "Vial",
							false,		// "Love Note",
							false,		// "Autopsy Report",
							false,		// "Pharmacy Pickup Receipt",
							false,		// "Pill Bottle",
							false,		// "Engagement Ring",
							false,		// "Bobby's Phone",
							false,		// "Lock Pick",
							false,		// "Flashlight",
							false,		// "Suspect List",
							false,		// "Trash",
							false,		// "Stuffed Creature",
							false,		// "Chair",
							false,		// "Table",
							false,		// "Booth",
							false,		// "Rags",
							false,		// "Shelves",
							false,		// "Bobby's Body",
							false,		// "Desk",
							false,		// "Coolers",
							false,		// "Freezers",
							false,		// "Shelves",
							false,		// "Bulletin Board",
							false,		// "Table",
							true,		// "Beth's Front Door",
							false,		// "Garden",
							false,		// "Table",
							false,		// "Box",
							false,		// "Bed",
							false,		// "Dresser",
							false,		// "Gnome",
							false,		// "Flamingos",
							true,		// "Claire's Front Door",
							false,		// "TV",
							false,		// "Rug",
							false,		// "Dresser",
							false,		// "Photographs",
							false,		// "Shrine",
							false,		// "Cans",
							false,		// "Water",
							false,		// "Car",
							false,		// "Chests",
							false,		// "Rags",
							true,		// "Bob's Front Door",
							false,		// "TV",
							false,		// "Posters",
							false,		// "Guitar",
							false,		// "Desk",
							false,		// "Jersey",
							false,		// "Computer",
							false,		// "Bed",
							false,		// "Dresser",
							false,		// "Bookshelf",
							false,		// "Nightstand",
							false,		// "Chimes",
							false,		// "Birdbath",
							false,		// "Cat",		
							true,		// "Sam's Front Door",	
							false,		// "Couch",	
							false,		// "Table",	
							false,		// "Newspaper",	
							false,		// "Entertainment Center",	
							false,		// "Bed",	
							false,		// "Newspapers",
							false,		// "Dresser",
							false,		// "Model Figurines",	
							false,		// "Medicine",	
							false,		// "Snacks",		
							false,		// "Desk",		
							true,		// "Laptop",
							false,		// "Truck",
							false,		// "Motorcycle",
							true,		// "Moose's Front Door",
							false,		// "Couch",
							false,		// "Table",
							false,		// "Newspapers",
							false,		// "Waterbed",
							false,		// "Blankets",
							false,		// "Table",
							false,		// "Dresser",
							false,		// "Beer Cans",
							false,		// "Clothes",
							false,		// "Chicken",
							true,		// "Trent's Front Door",
							false,		// "Couch",
							false,		// "Birdcage",
							false,		// "Bird",
							false,		// "Table",
							false,		// "Newspaper",
							false,		// "Beds",
							false,		// "Dresser",
							false,		// "Posters",
							false,		// "Drum Set",
							false,		// "Guitar"
							true,		// "Bunker Door"
							false,		// "Booze"
							false,		// "Code to Sam's Laptop",
							false,		// "Sam's Emails",
							false,		// "Bobby's Loan Application
							false,		// "Arrest Warrant"
							false,		// "Bed"
							true,		// "Hidden Room Door"
							false,		// "Empty Pill Bottle",
							false		// "Bunker Key"
						};	

vector<bool> objTakeStatus = {
							true,		// "Trevor's Wallet",
							true,		// "Vial",
							true,		// "Love Note",
							true,		// "Autopsy Report",
							true,		// "Pharmacy Pickup Receipt",
							true,		// "Pill Bottle",
							true,		// "Engagement Ring",
							true,		// "Bobby's Phone",
							true,		// "Lock Pick",
							true,		// "Flashlight",
							true,		// "Suspect List",
							false,		// "Trash",
							false,		// "Stuffed Creature",
							false,		// "Chair",
							false,		// "Table",
							false,		// "Booth",
							true,		// "Rags",
							false,		// "Shelves",
							false,		// "Bobby's Body",
							false,		// "Desk",
							false,		// "Coolers",
							false,		// "Freezers",
							false,		// "Shelves",
							false,		// "Bulletin Board",
							false,		// "Table",
							false,		// "Beth's Front Door",
							false,		// "Garden",
							false,		// "Table",
							false,		// "Box",
							false,		// "Bed",
							false,		// "Dresser",
							false,		// "Gnome",
							false,		// "Flamingos",
							false,		// "Claire's Front Door",
							false,		// "TV",
							false,		// "Rug",
							false,		// "Dresser",
							true,		// "Photographs",
							false,		// "Shrine",
							false,		// "Cans",
							false,		// "Water",
							false,		// "Car",
							false,		// "Chests",
							false,		// "Rags",
							false,		// "Bob's Front Door",
							false,		// "TV",
							false,		// "Posters",
							false,		// "Guitar",
							false,		// "Desk",
							false,		// "Jersey",
							true,		// "Computer",
							false,		// "Bed",
							false,		// "Dresser",
							false,		// "Bookshelf",
							false,		// "Nightstand",
							false,		// "Chimes",
							false,		// "Birdbath",
							false,		// "Cat",		
							false,		// "Sam's Front Door",	
							false,		// "Couch",	
							false,		// "Table",	
							false,		// "Newspaper",	
							false,		// "Entertainment Center",	
							false,		// "Bed",	
							false,		// "Newspapers",
							false,		// "Dresser",
							false,		// "Model Figurines",	
							true,		// "Medicine",	
							false,		// "Snacks",		
							false,		// "Desk",		
							true,		// "Laptop",
							false,		// "Truck",
							false,		// "Motorcycle",
							false,		// "Moose's Front Door",
							false,		// "Couch",
							false,		// "Table",
							false,		// "Newspapers",
							false,		// "Waterbed",
							false,		// "Blankets",
							false,		// "Table",
							false,		// "Dresser",
							false,		// "Beer Cans",
							false,		// "Clothes",
							false,		// "Chicken",
							false,		// "Trent's Front Door",
							false,		// "Couch",
							false,		// "Birdcage",
							false,		// "Bird",
							false,		// "Table",
							false,		// "Newspaper",
							false,		// "Beds",
							false,		// "Dresser",
							false,		// "Posters",
							false,		// "Drum Set",
							false,		// "Guitar"
							false,		// "Bunker Door"
							false,		// "booze"
							true,		// "Code to Sam's Laptop",
							true,		// "Sam's Emails",
							true,		// "Bobby's Loan Application"
							true,		// "Arrest Warrant"
							false,		// "Bed"
							false,		// "Hidden Room Door"
							false,		// "Empty Pill Bottle",
							true		// "Bunker Key"
						};

vector<bool> objInsight = {
							true,		// "Trevor's Wallet",
							true,		// "Vial",
							true,		// "Love Note",
							true,		// "Autopsy Report",
							true,		// "Pharmacy Pickup Receipt",
							true,		// "Pill Bottle",
							true,		// "Engagement Ring",
							true,		// "Bobby's Phone",
							true,		// "Lock Pick",
							true,		// "Flashlight",
							true,		// "Suspect List",
							false,		// "Trash",
							false,		// "Stuffed Creature",
							false,		// "Chair",
							false,		// "Table",
							false,		// "Booth",
							false,		// "Rags",
							false,		// "Shelves",
							false,		// "Bobby's Body",
							false,		// "Desk",
							false,		// "Coolers",
							false,		// "Freezers",
							false,		// "Shelves",
							false,		// "Bulletin Board",
							false,		// "Table",
							false,		// "Beth's Front Door",
							false,		// "Garden",
							false,		// "Table",
							false,		// "Box",
							false,		// "Bed",
							false,		// "Dresser",
							false,		// "Gnome",
							false,		// "Flamingos",
							false,		// "Claire's Front Door",
							false,		// "TV",
							false,		// "Rug",
							false,		// "Dresser",
							false,		// "Photographs",
							false,		// "Shrine",
							false,		// "Cans",
							false,		// "Water",
							false,		// "Car",
							false,		// "Chests",
							false,		// "Rags",
							false,		// "Bob's Front Door",
							false,		// "TV",
							false,		// "Posters",
							false,		// "Guitar",
							false,		// "Desk",
							false,		// "Jersey",
							false,		// "Computer",
							false,		// "Bed",
							false,		// "Dresser",
							false,		// "Bookshelf",
							false,		// "Nightstand",
							false,		// "Chimes",
							false,		// "Birdbath",
							false,		// "Cat",		
							false,		// "Sam's Front Door",	
							false,		// "Couch",	
							false,		// "Table",	
							false,		// "Newspaper",	
							false,		// "Entertainment Center",	
							false,		// "Bed",	
							false,		// "Newspapers",
							false,		// "Dresser",
							false,		// "Model Figurines",	
							false,		// "Medicine",	
							false,		// "Snacks",		
							false,		// "Desk",		
							false,		// "Laptop",
							false,		// "Truck",
							false,		// "Motorcycle",
							false,		// "Moose's Front Door",
							false,		// "Couch",
							false,		// "Table",
							false,		// "Newspapers",
							false,		// "Waterbed",
							false,		// "Blankets",
							false,		// "Table",
							false,		// "Dresser",
							false,		// "Beer Cans",
							false,		// "Clothes",
							false,		// "Chicken",
							false,		// "Trent's Front Door",
							false,		// "Couch",
							false,		// "Birdcage",
							false,		// "Bird",
							false,		// "Table",
							false,		// "Newspaper",
							false,		// "Beds",
							false,		// "Dresser",
							false,		// "Posters",
							false,		// "Drum Set",
							false,		// "Guitar"
							true,		// "Bunker Door"
							false,		// "Booze"
							true, 		// "Code",
							true,		// "Emails",
							true,		// "Loan Application"
							true,		// "Arrest Warrant"
							false,		// "Bed"
							false,		// "Hidden Room Door"
							true,		// "Empty Pill Bottle",
							true		// "Bunker Key"
						};	
						
vector<bool> objHiddenStatus = {
							false,		// "Trevor's Wallet",
							true,		// "Vial",
							false,		// "Love Note",
							false,		// "Autopsy Report",
							true,		// "Pharmacy Pickup Receipt",
							false,		// "Pill Bottle",
							false,		// "Engagement Ring",
							false,		// "Bobby's Phone",
							false,		// "Lock Pick",
							false,		// "Flashlight",
							false,		// "Suspect List",
							false,		// "Trash",
							false,		// "Stuffed Creature",
							false,		// "Chair",
							false,		// "Table",
							false,		// "Booth",
							false,		// "Rags",
							false,		// "Shelves",
							false,		// "Bobby's Body",
							false,		// "Desk",
							false,		// "Coolers",
							false,		// "Freezers",
							false,		// "Shelves",
							false,		// "Bulletin Board",
							false,		// "Table",
							false,		// "Beth's Front Door",
							false,		// "Garden",
							false,		// "Table",
							false,		// "Box",
							false,		// "Bed",
							false,		// "Dresser",
							false,		// "Gnome",
							false,		// "Flamingos",
							false,		// "Claire's Front Door",
							false,		// "TV",
							false,		// "Rug",
							false,		// "Dresser",
							false,		// "Photographs",
							false,		// "Shrine",
							false,		// "Cans",
							false,		// "Water",
							false,		// "Car",
							false,		// "Chests",
							false,		// "Rags",
							false,		// "Bob's Front Door",
							false,		// "TV",
							false,		// "Posters",
							false,		// "Guitar",
							false,		// "Desk",
							false,		// "Jersey",
							false,		// "Computer",
							false,		// "Bed",
							false,		// "Dresser",
							false,		// "Bookshelf",
							false,		// "Nightstand",
							false,		// "Chimes",
							false,		// "Birdbath",
							false,		// "Cat",		
							false,		// "Sam's Front Door",	
							false,		// "Couch",	
							false,		// "Table",	
							false,		// "Newspaper",	
							false,		// "Entertainment Center",	
							false,		// "Bed",	
							false,		// "Newspapers",
							false,		// "Dresser",
							false,		// "Model Figurines",	
							false,		// "Medicine",	
							false,		// "Snacks",		
							false,		// "Desk",		
							false,		// "Laptop",
							false,		// "Truck",
							false,		// "Motorcycle",
							false,		// "Moose's Front Door",
							false,		// "Couch",
							false,		// "Table",
							false,		// "Newspapers",
							false,		// "Waterbed",
							false,		// "Blankets",
							false,		// "Table",
							false,		// "Dresser",
							false,		// "Beer Cans",
							false,		// "Clothes",
							false,		// "Chicken",
							false,		// "Trent's Front Door",
							false,		// "Couch",
							false,		// "Birdcage",
							false,		// "Bird",
							false,		// "Table",
							false,		// "Newspaper",
							false,		// "Beds",
							false,		// "Dresser",
							false,		// "Posters",
							false,		// "Drum Set",
							false,		// "Guitar"
							true,		// "Bunker Door"
							false,		// "Booze"
							true,		// "Code to Sam's Laptop",
							true,		// "Sam's Emails",
							true,		// "Bobby's Loan Application
							false,		// "Arrest Warrant"
							false,		// "Bed"
							true,		// "Hidden Room Door"
							false,		// "Empty Pill Bottle",
							true		// "Bunker Key"
						};	

		
	// create all objects
	vector<string> vVerbs {"look", "take", "help", "hint", "inventory", "use", "drop"};						

//MACRO for creating rooms for the game
#define CREATE_ROOM(var_name,var_enum) \
			shared_ptr<Room> var_name(new Room (\
												 roomName[var_enum], roomDisplayName[var_enum], roomShortDesc[var_enum], \
												 roomLongDesc[var_enum], roomObjs[var_enum], people[var_enum], 0)); \
									  listRoom.push_back(var_name)

//MACRO for creating characters for the game									  
#define CREATE_CHAR(var_name,var_enum) \
			shared_ptr<Character> var_name(new Character (\
															characterName[var_enum], charDisplayName[var_enum], charLongDesc[var_enum], \
															0, charDialog[var_enum])); \
										  listCharacter.push_back(var_name)
//MACRO for creating objects for the game
#define CREATE_OBJ(var_name,var_enum)   \
			shared_ptr<Object> var_name (new Object (objName[var_enum], objDisplayName[var_enum], objLongDesc[var_enum], \
												vVerbs, objTakeStatus[var_enum], objLockedStatus[var_enum], \
												objInsight[var_enum], objHiddenStatus[var_enum]));\
										listObject.push_back(var_name)
		
		
#endif